name: env
channels:
  - defaults
dependencies:
  - python=3.9.6 
  - pip
  - pip:
    - opencv-python
    - "mediapipe<0.10.2"
    - pyatv
    - "protobuf<4,>=3.11"
    - scikit-learn
    - tensorflow
    - pydot
    - graphviz
    - wandb
